version: '3'
services:
  postgres:
    image: mdillon/postgis:10 # <- here
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
      POSTGRES_NAME: "test"
    volumes:
      - ./scripts:/scripts
      

